Resources:
  # Create a new IAM policy that allows the task role to put logs to CloudWatch
  CloudWatchAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${App}-${Env}-${Name}-CloudWatchAccessPolicy
      Roles:
      - !Ref TaskRole
PolicyDocument:
  Version: '2012-10-17'
  Statement:
  - Effect: Allow
  Action:
  - logs:CreateLogGroup
  - logs:CreateLogStream
  - logs:PutLogEvents
Resource: '*'